spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/onepiece?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 最大连接数，缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 30
      # 最小连接数
      minimum-idle: 10
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1800000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
  sql:
    init:
      mode: never

mall:
  jd:
    auth-url: https://open-oauth.jd.com/oauth2
    server-url: https://api.jd.com/routerjson
  jd-bill:
    auth-url: https://bizapi.jd.com/oauth2
    server-url: http://cvop.jd.com/component/http/JSON
  sn:
    server-url: https://open.suning.com/api/http/sopRequest
  zkh:
    server-url: https://zkh.com
