server:
  port: 8080

spring:
  application:
    name: op-admin
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onepiece?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 最大连接数，缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 30
      # 最小连接数
      minimum-idle: 10
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1800000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
        # 最大等待时间
        max-wait: -1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: logs
    name: ${user.home}/logs/admin.log

mybatis:
  configuration:
    database-id: mysql
    map-underscore-to-camel-case: true

swagger:
  app-name: Sdk Client Web Demo
  app-desc: Sdk Client Web Demo
  app-version: 1.0
  try-host: http://localhost:${server.port}