server:
  port: 8082

spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

mybatis:
  configuration:
    database-id: mysql
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
