server:
  port: 8082

spring:
  profiles:
    active: local
  task:
    execution:
      pool:
        core-size: 13
        max-size: 300

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

mybatis:
  configuration:
    database-id: mysql
    map-underscore-to-camel-case: true