server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # RSA 公钥访问地址
          #          jwk-set-uri: 'http://localhost:8081/oauth2/jwks'
          jwk-set-uri: 'http://localhost:8081/.well-known/jwks.json'
  #          issuer-uri: 'http://localhost:8081'
  cloud:
    gateway:
      routes:
        - id: op-auth
          uri: http://localhost:8081
          predicates:
            - Path=/op-auth/**
          filters:
            - StripPrefix=1
        - id: op-admin
          uri: http://localhost:8082
          predicates:
            - Path=/op-admin/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

secure:
  white-list:
    urls:
      - "/op-auth/oauth/token"
      - "/op-admin/captcha"
      - "/op-admin/user/login"
      - "/op-admin/user/register"