spring:
    redis:
      host: host.docker.internal
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}