server:
  port: 8081

spring:
  profiles:
    active: dev

feign:
  client:
    config:
      default:
        # 默认 2s，建议 1~5 秒
        connectTimeout: 2000
        # 默认 5s，建议 <= 30s
        readTimeout: 30000
  ## 启用 httpclient 连接池
  httpclient:
    enabled: true

${spring.applicationname}:
  ribbon:
    # 同一台服务器上的最大重试次数（不包括第一次尝试），默认值 0
    MaxAutoRetries: 1
    # 要重试的下一个服务器的最大数量（不包括第一个服务器），默认值 1
    MaxAutoRetriesNextServer: 1
    # 可以根据接口返回的状态码判断是否重试
    # retryableStatusCodes: 500,404
    # 对所有的超时请求重试（包括 POST 等请求），默认值 false
    OkToRetryOnAllOperations: false

encryption:
  key-store:
    location: keys.keystore
    secret: admin123
    alias: yoyo-mall-certificate
    password: admin123